baseURL: "https://Zhao-Huazhou.github.io/"
languageCode: "zh-cn"
title: "Aiden Zhao"
theme: "PaperMod"

params:
  defaultTheme: auto
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  TocOpen: false
  assets:
    favicon: "/favicon.ico"

menu:
  main:
    - name: "文章"
      url: "/posts/"
      weight: 1
    - name: "标签"
      url: "/tags/"
      weight: 2
    - name: "关于"
      url: "/about/"
      weight: 3
